[package]
name = "cli-chan"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "3.0.0"
log = "0.4.27"
reqwest = "0.12.22"
serde = { version = "1.0.219", features = ["derive"]}
serde_json = "1.0.141"
tokio = { version = "1.47.0", features = ["full"] }
